<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TC1ANB6" failures="2" tests="6" name="Test" time="0.427" errors="0" timestamp="2025-07-14T12:32:03 IST">
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase1" time="0.041">
    <failure type="java.lang.AssertionError" message="expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [2]
at com.ka.practice.KA15LoginPageTestCases.TestCase1(KA15LoginPageTestCases.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase2" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.ka.practice.KA15LoginPageTestCases.TestCase2(KA15LoginPageTestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestCase2 -->
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase3" time="0.004"/>
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase4" time="0.018"/>
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase5" time="0.012">
    <skipped/>
  </testcase> <!-- TestCase5 -->
  <testcase classname="com.ka.practice.KA15LoginPageTestCases" name="TestCase6" time="0.035"/>
</testsuite> <!-- Test -->
